#!/usr/bin/env bash

HERE="`pwd`"

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"


# Based on this article: https://sookocheff.com/post/bash/parsing-bash-script-arguments-with-shopts/

target="."  # Default to current location

if [ $# == 0 ]; then
    echo "Error: No parameters passed. Try -h"
fi

while getopts ":h" opt; do
    case ${opt} in
        h )
            echo "Usage:"
            echo "    GATTACA -h             Display this help message."
            echo "    GATTACA init           Spawn a default configuration file."
            echo "    GATTACA run            Run GATTACA."
            echo "    GATTACA prepaffy       Run the preprocessing scripts for Affymetrix .CEL files"
            echo "    GATTACA prepagil       Run the preprocessing scripts for Agilent .txt and target files."
            echo ""
            echo "Use -h in any subcommand to get more help and possible options"
            exit 0
            ;;
        \? )
            echo "Invalid Option: -$OPTARG" 1>&2
            exit 1
            ;;
    esac
done
shift $((OPTIND -1))

subcommand=$1; shift  # Remove 'subcommand` from the argument list
case "$subcommand" in
    init)
        # Process init options
        while getopts ":t:h" opt; do
            case ${opt} in
                t )
                    target=$OPTARG
                    target=$(realpath $target)
                    if [ -f $target ]; then
                        # The target is a file. Copy it there
                        cp "${DIR}/GATTACA_default_options.yaml" ${target}
                        echo "Spawned config file: ${target}"
                        exit 0
                    elif [ -d $target ]; then
                        # The target is a directory. Copy it there
                        cp "${DIR}/GATTACA_default_options.yaml" "${target}/GATTACA_config.yaml"
                        echo "Spawned config file: ${target}/GATTACA_config.yaml"
                    else
                        # The path is invalid.
                        echo "Invalid path: ${target}"
                        exit 1
                    fi
                    exit 0
                    ;;
                h )
                    echo "Create a default configuration file for GATTACA in the current working directory."
                    echo ""
                    echo "If unspecified, the default name is GATTACA_config.yaml"
                    echo "Usage:"
                    echo "    GATTACA init                  Create the configuration file in the current working dir."
                    echo "    GATTACA init -h               Display this help message."
                    echo "    GATTACA init -t <path>        Create the configuration file in the target folder"
                    echo "                                  or as the target file."
                    exit 0
                    ;;
                \? )
                    echo "Invalid Option: -$OPTARG" 1>&2
                    exit 1
                    ;;
                : )
                    # The target is the current working directory. Copy it there
                    cp "${DIR}/GATTACA_default_options.yaml" "${target}/GATTACA_config.yaml"
                    echo "Spawned config file: ${target}/GATTACA_config.yaml"
                    exit 0
                    ;;
            esac
        done
        shift $((OPTIND -1))
        ;;
    run)
        # Default options
        version="latest"
        target=$(realpath "./GATTACA_output")
        optfile=$(realpath "./GATTACA_config.yaml")
        inputfile=$(realpath "./inputfile")
        while getopts ":hi:t:o:v:" opt; do
            case ${opt} in
                t ) target=$(realpath $OPTARG);;
                i ) inputfile=$(realpath $OPTARG);;
                o ) optfile=$(realpath $OPTARG);;
                v ) version=$OPTARG ;;
                h )
                    echo "Download and run the GATTACA docker container."
                    echo ""
                    echo "Options:"
                    echo "    -h                            Display this help message."
                    echo "    -t <target_folder>            Set the output folder. Defaults to ./GATTACA_output/"
                    echo "    -i <input_file>               Specify the input file path with the microarray intensities."
                    echo "    -o <options_file>             Set the options file. Defaults to ./GATTACA_config.yaml"
                    echo "                                  NOTE: Due to docker limitations, the options file will be"
                    echo "                                  copied to the input folder, and it must not have the same" echo "                                  name as the input file."
                    echo "    -v <docker version>           Set the version of the docker to use. Defaults to latest."
                    exit 0
                    ;;
                \? )
                    echo "Invalid Option: -$OPTARG" 1>&2
                    exit 1
                    ;;
                : ) : ;;
            esac
        done
        shift $((OPTIND -1))
        # Test if the options are valid
        ## Target folder
        if [ -f $target ]; then
            # The target is a file. Error
            echo "Error: Output folder (${target}) cannot be a file."
            exit 1
        elif [ ! -d $target ]; then
            # The target is a directory that doesn't exist. Make it.
            mkdir -p $target
            echo "Made output folder: ${target}"
        elif [ -d $target ]; then
            # The target is a real folder, wow
            echo "Using output folder: ${target}"
        else
            # The path is invalid.
            echo "Error: invalid output path: ${target}"
            exit 1
        fi
        ## Input file
        if [ -d $inputfile ]; then
            # The input is a folder. Error
            echo "Error: Input file (${inputfile}) cannot be a folder."
            exit 1
        elif [ -f $inputfile ]; then
            # The input is a file. OK
            echo "Using input file: ${inputfile}"
        else
            # The path is invalid.
            echo "Error: invalid input path: ${inputfile}"
            exit 1
        fi
        ## Options file
        if [ -d $optfile ]; then
            # The options is a folder. Error
            echo "Error: Options file (${optfile}) cannot be a folder."
            exit 1
        elif [ -f $optfile ]; then
            # The options is a file. OK
            echo "Using options file: ${optfile}"
        else
            # The path is invalid.
            echo "Error: invalid options path: ${optfile}"
            exit 1
        fi
        echo "Using version ${version}"
        shift $((OPTIND -1))

        # Now that we have the options we can fetch the container, mount the
        # exit directory, and run the container.

        input_mountpoint="$(dirname "$inputfile")"
        input_file_clean=$(basename -- "$inputfile")
        option_file_clean=$(basename -- "$optfile")

        if [ "${input_file_clean}" = "${option_file_clean}" ]; then
            echo "Input and option files cannot have the same name. Sorry!"
            exit 1
        fi

        echo "Mounting folders:"
        echo "      Inputs:  ${input_mountpoint}"
        echo "      Outputs: ${target}"

        # To avoid mountig the same folder multiple times, I copy the options 
        # file to the input folder just to be safe.
        if [ ! $optfile = "${input_mountpoint}/${option_file_clean}" ]; then
            cp $optfile "${input_mountpoint}/${option_file_clean}"
        fi

        docker run \
            -it --rm \
            --mount type=bind,source=$target,target=/GATTACA/target \
            --mount type=bind,source=$input_mountpoint,target=/GATTACA/input,readonly \
            mrhedmad/gattaca:$version \
            "gattaca" $input_file_clean $option_file_clean

        ;;
    prepaffy)
        # Default options
        inputFolder="."
        outputFile="./AffyExpression.txt"
        logName="NULL"
        removeControls="FALSE"
        version="latest"
        
        while getopts ":i:o:l:v:arh" opt; do
            case ${opt} in
                i) inputFolder=$(realpath $OPTARG);;
                o) outputFile=$OPTARG;;
                l) logName=$OPTARG;;
                r) removeControls="TRUE";;
                v) version=$OPTARG ;;
                h)
                    echo "Run preprocessing on .CEL files to get an expression matrix."
                    echo ""
                    echo "Options:"
                    echo "  -h                      Print this message and exit."
                    echo "  -i <input folder>       Specify the input folder with a collection of .CEL files"
                    echo "                          Defaults to the current working directory."
                    echo "  -o <output file>        Specify the output file that will contain the expression matrix"
                    echo "                          Defaults to '${outputfile}'"
                    echo "  -l <log filename>       Specify the filename of the log that will be alongside the output file."
                    echo "  -v <docker version>     Set the version of the docker to use. Defaults to latest."
                    echo ""
                    echo "Flags:"
                    echo "  -r        If set, will remove control probes from the final set."
                    exit 0
                ;;
                \?)
                    echo "Invalid Option: -$OPTARG" 1>&2
                    exit 1
                ;;
                :) : ;;
            esac
        done
        shift $((OPTIND -1))
        # Test if the options are valid
        ## Input folder
        if [ -f $inputFolder ]; then
            # The target is a file. Error
            echo "Error: Input folder (${inputFolder}) cannot be a file."
            exit 1
        elif [ ! -d $inputFolder ]; then
            # The target is a directory that doesn't exist. Error.
            echo "Error: Input folder (${inputFolder}) doesn't exist."
            exit 1
        elif [ -d $inputFolder ]; then
            # The target is a real folder, wow
            echo "Using input folder: ${inputFolder}"
        else
            # The path is invalid.
            echo "Error: invalid input path: ${inputFolder}"
            exit 1
        fi
        ## Check if the output folder exists.
        outputFolder="$(dirname "$outputFile")"
        if [ ! -d $outputFolder ]; then
            # The foldes doesn't exist. Make it.
            mkdir -p $outputFolder
            echo "Made output folder: ${outputFolder}"
        elif [ -d $outputFolder ]; then
            # The outputFolder is a real folder, wow
            echo "Using output file: ${outputFile}"
        else
            # The path is invalid.
            echo "Error: invalid output path: ${outputFile}"
            exit 1
        fi
        echo "Using version: ${version}"
        echo "Using logname: ${logName}"
        echo "Remove control probes? ${removeControls}"

        output_file_clean=$(basename -- "$outputFile")

        # Now that we have the options, we can start the docker container.
        docker run \
            -it --rm \
            --mount type=bind,source=$outputFolder,target=/GATTACA/target \
            --mount type=bind,source=$inputFolder,target=/GATTACA/input,readonly \
            mrhedmad/gattaca:$version \
            "prepaffy" $output_file_clean $logName $removeControls
        exit 0
        ;;
    annotate)
        # Default options
        # "$input_file_clean $output_file_clean $chip_id $selections $logname"
        inputFile=""
        outputFile="./annotated_expressions.csv"
        chipID=""
        logName="NULL"
        selections=""
        version="latest"
        
        while getopts ":i:o:c:l:v:s:h" opt; do
            case ${opt} in
                i) inputFile=$(realpath $OPTARG);;
                o) outputFile=$(realpath $OPTARG);;
                l) logName=$OPTARG;;
                c) chipID=$OPTARG;;
                s) selections=$OPTARG ;;
                v) version=$OPTARG ;;
                h)
                    echo "Annotate an expression dataset."
                    echo ""
                    echo "Options:"
                    echo "  -h                      Print this message and exit."
                    echo "  -i <input file>         Specify the input file to annotate."
                    echo "  -o <output file>        Specify the output file path."
                    echo "  -c <chip id>            Specify the chip id. See the readme for a list of supported chips."
                    echo "  -l <log filename>       Specify the filename of the log that will be alongside the output file."
                    echo "  -v <docker version>     Set the version of the docker to use. Defaults to latest."
                    echo ""
                    echo "Flags:"
                    echo "  -r        If set, will remove control probes from the final set."
                    exit 0
                ;;
                \?)
                    echo "Invalid Option: -$OPTARG" 1>&2
                    exit 1
                ;;
                :) : ;;
            esac
        done
        

        echo "Using logname: ${logName}"
        echo "Using chip id: ${chipID}"
        
        output_file_clean=$(basename -- "$outputFile")
        outputFolder="$(dirname "$outputFile")"
        input_file_clean=$(basename -- "$inputFile")
        inputFolder="$(dirname "$inputFile")"
        
        # Now that we have the options, we can start the docker container.
        # "$input_file_clean $output_file_clean $chip_id $selections $logname"
        docker run \
            -it --rm \
            --mount type=bind,source=$outputFolder,target=/GATTACA/target \
            --mount type=bind,source=$inputFolder,target=/GATTACA/input,readonly \
            gattaca:$version \
            "annotate" $input_file_clean $output_file_clean $chipID $selections $logName
        
        exit 0
        ;;
    prepagil)
        echo "This is not yet implemented. Sorry!"
        exit 0
        ;;
esac
