#!/usr/bin/env bash

version="latest"

if [ "$1" = "-v" ] || [ "$1" = "--version" ]; then
    version=$2
    # No shifts are needed here, the arg is passed also to the evaluated
    # script, as-is.

    # Test that there are no more '-v/--version's around.
    # The "${@:2:$#}" starts iterating from the 2rd element (to skip the first
    # -v/--version we already found).
    for i in "${@:2:$#}"; do
        if [ "$i" = "-v" ] || [ "$i" = "--version" ]; then
            echo "ERROR: Version argument ($i) found multiple times."
            exit 1
        fi
    done
else
    # Same as above, but tests it everywhere in the string.
    for i in "$@"; do
        if [ "$i" = "-v" ] || [ "$i" = "--version" ]; then
            echo "ERROR: Version argument ($i) was not the first one passed."
            exit 1
        fi
    done
fi

echo "Running with version '$version'."

# This captures the version-specific script that gives the CLI for GATTACA
# and runs it as code, so that this script will (almost) never have to be
# updated by the user.
GATTACA_CLI="$(docker run --rm cmalabscience/gattaca:"$version" getcli)"
if [ $? -ne 0 ]; then
    echo "$GATTACA_CLI"
    exit 1
fi
eval "$GATTACA_CLI"
