#!/bin/bash

# Take out the order from the GATTACA script, defining what we have to do.
order=$1; shift # This gets rid of $1 containig the order.

case "$order" in
    gattaca)
        ## As this should only be run from the main GATTACA file, we can be sure that
        # $1 is input_file_clean and $2 is option_file_clean, both in /GATTACA/input
        # We are also sure that we need to write to /GATTACA/target
        inputfile="/GATTACA/input/${1}"
        optionfile="/GATTACA/input/${2}"

        Rscript \
            --vanilla \
            -e "source('/GATTACA/src/__init__.R')" \
            -e "source('/GATTACA/src/GATTACA.R')" \
            -e "GATTACA('${optionfile}', '${inputfile}', '/GATTACA/target')"
        ;;
    prepaffy)
        ## Again, we know the order of the iputs:
        # "$output_file_clean $logname $useAffy $removeControls"
        outputfile="/GATTACA/target/${1}"

        Rscript \
            --vanilla \
            -e "source('/GATTACA/src/__init__.R')" \
            -e "source('/GATTACA/src/toExpression/Affy_CEL_to_Expression.R')" \
            -e "affy2expression('/GATTACA/input', '${outputfile}', log_name = '${2}', remove.controls = ${3})"
        ;;
    *)
        echo "Unrecognized order: '${order}'"
        exit 1
        ;;
esac
